services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql-data
    environment:
      POSTGRES_DB: ktor_journal
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54333:5432"
    healthcheck:
      test: [ "CMD_SHELL", "pg_isready", "-U postgres" ]
      interval: 1s
